AWSTemplateFormatVersion: 2010-09-09
Description: "A codebuild system to run terraform "
Parameters:
  DataPartName:
    Description: the data part name as appear in the cloudformation stack name
    Type: String
    Default: mydataname
Resources:
  S3StateAndSoftware:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - .
          - - Ref: DataPartName
            - Ref: AWS::Region
            - terraform-state-software
  Adminrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
          - .
          - - Ref: AWS::StackName
            - Ref: AWS::Region
            - codebuild
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: "*"
                Effect: Allow
                Resource: "*"
          PolicyName: adminaccess
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Join:
          - _
          - - Ref: AWS::StackName
            - Ref: AWS::Region
            - TF_Apply
      Description: build the application part for cades using terraform
      ServiceRole:
        Ref: Adminrole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        EnvironmentVariables:
          - Name: datapart
            Value:
              Ref: DataPartName
          - Name: region
            Value:
              Ref: AWS::Region
          - Name: applicationname
            Value:
              Ref: AWS::StackName
          - Name: destroy
            Value: "False"
      Source:
        Location: https://github.com/jair-chen/run-terraform-inside-aws-codebuild
        Type: GITHUB
      TimeoutInMinutes: 10
      Tags:
        - Key: Project
          Value: Run Terraform From CodeBuild
